### PR TITLE
case sensitivity on user emails

### PR DESCRIPTION
**Pull request by mathis-marcotte**
might close https://github.com/StatCan/daaas/issues/127 (must test ofc)

### CODE REVIEW

**Comment by Jose-Matsuda** [comment]
Ok I've done a fair bit of focused digging, please let me know if I am making any sense I can post a follow-up comment if not.

## Few steps to find out where I am in knowledge
1. At the argocd layer we deploy `kubeflow` [here using an applicationset](https://github.com/StatCan/aaw-argocd-manifests/blob/aaw-dev-cc-00/kubeflow/kubeflow.jsonnet) 
2. So we go to the referenced [repoUrl](https://github.com/StatCan/aaw-argocd-manifests/blob/3cf92eb265e0883d385962a9a67f08297a05a5ec/kubeflow/kubeflow.jsonnet#L130) 
3. Search for anything kfam related and end up in this [issue](https://github.com/StatCan/aaw-kubeflow-manifests/issues/123) and it turns out that it is instead in some `profiles`[component](https://github.com/StatCan/aaw-kubeflow-manifests/pull/141/files#diff-03d6e1c389dd044060b5d89306a9fa78dbd2c94c9b7fa4234520d22648ecb38cR12)
4. So we look in our [kustomization](https://github.com/StatCan/aaw-kubeflow-manifests/blob/5be34fe3d7834c4f8ac910adccf977b26ab18477/kustomize/apps/profiles/base/kustomization.yaml#L6) which references upstream.
5. And lo and behold it exists [here](https://github.com/kubeflow/manifests/blob/42a19c0825d23149c0edb67757b04a635d6a26f0/apps/profiles/upstream/overlays/kubeflow/kustomization.yaml#L29)


## Next Steps in order to test the image. 
So it appears that we did switch to using the upstream image. So we will need to 

- [x] build this `access-management` image in our branch
- [x] Turn _off autosync_ in argocd dev at the `kubeflow` application level in order to make an edit to the `profiles-deployment` `Deployment` to make a change to the `image`
image
- [ ] Refresh and try things out, see if it performs as expected
- [ ] Iff it does, we can make the change permanent by changing up the `kustomize` that deploys this, and bring it to Prod too (by making the change in the prod branch as well).


### Other relevant information
Our fork of [kubeflow](https://github.com/StatCan/kubeflow) is _at version 1.3_, so when we upgrade we will need to evaluate and check that everything works as intended.
We may want to hold off on deploying this fix to prod if that is the case.

**Comment by Jose-Matsuda** [comment]
There's a double `build-push` because I kept this `case-sensitivity-emails` in the branchname, will remove it and just keep it as the build on pr / push to stc-master.

But this issue of the docker build failing is a tad more concerning, will need to investigate

**Comment by Jose-Matsuda** [comment]
I can make it past the first failure by upgrading the golang version to be 1.17 like they do [upstream](https://github.com/kubeflow/kubeflow/blob/e7d34b7dec5c75875e728a7b065e62e71a9a4208/components/access-management/Dockerfile#L1) but now have a new one at 

image

oh might need to update go.mod

**Comment by mathis-marcotte** [comment]
The solution taken was to forcefully lowercase the emails on profile and rolebinding creation. Investigation was done to try to remove case sensitivity, but that assumption is really built into kubernetes.

A case that wasn't tested is situations where a user actually has capital letters in their email, since I personally didn't have an email like that to use.

**Review by Jose-Matsuda — APPROVED** [review]
lgtm, as stated unsure about "how profiles already created with capital letters in it will act. If they don't actually work as expected, it might be either return to the drawing board or probably a better option would just be to fix it case by case in the profile objects already saved".

We _might_ need to make a script to lowercase all the existing `Profile` and `User` crds to make sure they are compatible with this cross-cutting change.

**Pull request merged**
